// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhtO17oj5ic4nbu2kQk6tPNLBp5q_KO0c',
    appId: '1:818212556234:web:77137586a506248dbbd333',
    messagingSenderId: '818212556234',
    projectId: 'footballbranding-9d2f8',
    authDomain: 'footballbranding-9d2f8.firebaseapp.com',
    storageBucket: 'footballbranding-9d2f8.firebasestorage.app',
    measurementId: 'G-LB0329H9FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQXVxvizlKcdKCl6leVzdJBGsVA_M-5ao',
    appId: '1:818212556234:android:21d7a212af905540bbd333',
    messagingSenderId: '818212556234',
    projectId: 'footballbranding-9d2f8',
    storageBucket: 'footballbranding-9d2f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgjNLser_1Hw97W2Fnh5AvYjfOy8HJoFQ',
    appId: '1:818212556234:ios:5826bf55c1fbf7d8bbd333',
    messagingSenderId: '818212556234',
    projectId: 'footballbranding-9d2f8',
    storageBucket: 'footballbranding-9d2f8.firebasestorage.app',
    iosBundleId: 'com.example.k5BrandingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgjNLser_1Hw97W2Fnh5AvYjfOy8HJoFQ',
    appId: '1:818212556234:ios:5826bf55c1fbf7d8bbd333',
    messagingSenderId: '818212556234',
    projectId: 'footballbranding-9d2f8',
    storageBucket: 'footballbranding-9d2f8.firebasestorage.app',
    iosBundleId: 'com.example.k5BrandingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhtO17oj5ic4nbu2kQk6tPNLBp5q_KO0c',
    appId: '1:818212556234:web:213ee77b57301d73bbd333',
    messagingSenderId: '818212556234',
    projectId: 'footballbranding-9d2f8',
    authDomain: 'footballbranding-9d2f8.firebaseapp.com',
    storageBucket: 'footballbranding-9d2f8.firebasestorage.app',
    measurementId: 'G-CQ6H49MGHJ',
  );

}